### ISSUE TITLE
bug: Complexity score doesn't appear to minimize complexity

### ISSUE THREAD

**Issue by highlyunavailable** [lydianlights/yet-another-factory-planner#1]
Related to this reddit comment thread:

https://www.reddit.com/r/SatisfactoryGame/comments/r50pd4/i_made_a_shiny_new_production_calculator_geared/hmlq2kk/

Complexity metric should minimize the number of distinct input items or something similar.

**Comment by lunafoxfire** [comment]
Ah yes, this is something I'm still working on. The way complexity works currently is that it minimizes the total number of inputs for each recipe multiplied by the number of copies of that recipe. This doesn't produce as intuitive results as I would like though.

Unfortunately due to the technicalities of the way the solver works it's difficult to formulate optimization rules about certain types of features, including global features like "least number of overall input items" that would make the most sense to measure complexity. (For more detail, the solver formulates the problem in terms of a [linear optimization](https://en.wikipedia.org/wiki/Linear_programming) problem, which has strict rules about the form of the objective function.

**Comment by lunafoxfire** [comment]
Further updates on this issue: I have a way to solve this issue with a better definition of complexity. However, due to the mathematics of the problem it becomes EXTREMELY slow (or inaccurate if I set a time limit) for large factories. I will continue working on this though because I really want this feature to work properly.

**Comment by lunafoxfire** [comment]
I'm going to go ahead and close this as resolved, as the logic I have in place now is likely the final version.
