### ISSUE TITLE
feature: Make All/None buttons respect the search input

### ISSUE THREAD

**Issue by highlyunavailable** [lydianlights/yet-another-factory-planner#3]
If I click "Select None" with search results, it clears every single selected recipe.

Expected behavior:

If I click Select All or Select None with a recipe filter, it only enables/disables the recipes that match the filter.

**Comment by lunafoxfire** [comment]
Not exactly a bug, since this is how I intended it to work. Perhaps the expected behavior needs to be clarified though. Or maybe the behavior you described is more desirable? Do you feel like it would be useful to "select all" or "select none" on only the searched subset of recipes? I could see a case being made for this being the behavior.

**Comment by highlyunavailable** [comment]
I'll change this to feature then. I'd expect the "Select all/none" to apply to _only recipes I can currently see_ I guess is how I'd describe it.
